// Effect display list stub - sized for 10 commands (80 ROM bytes)
// Auto-generated by gen_effect_gfx_data.py
// One slot longer than ROM (+ 1 spare): lists that fall through to the next chunk on N64
// get an explicit branch written there, since these are separate arrays here.
Gfx D_09001D00_37F6D0[11] = {
    gsSPEndDisplayList(),
};
