// Effect display list stub - sized for 15 commands (120 ROM bytes)
// Auto-generated by gen_effect_gfx_data.py
// One slot longer than ROM (+ 1 spare): lists that fall through to the next chunk on N64
// get an explicit branch written there, since these are separate arrays here.
Gfx D_090053C0_3EB2F0[16] = {
    gsSPEndDisplayList(),
};
