// Effect display list stub - sized for 47 commands (376 ROM bytes)
// Auto-generated by gen_effect_gfx_data.py
// One slot longer than ROM (+ 1 spare): lists that fall through to the next chunk on N64
// get an explicit branch written there, since these are separate arrays here.
Gfx D_09003398_3C0D38[48] = {
    gsSPEndDisplayList(),
};
