// Effect display list stub - sized for 38 commands (304 ROM bytes)
// Auto-generated by gen_effect_gfx_data.py
// One slot longer than ROM (+ 1 spare): lists that fall through to the next chunk on N64
// get an explicit branch written there, since these are separate arrays here.
Gfx D_09001650_333CF0[39] = {
    gsSPEndDisplayList(),
};
