// Effect display list stub - sized for 91 commands (728 ROM bytes)
// Auto-generated by gen_effect_gfx_data.py
// One slot longer than ROM (+ 1 spare): lists that fall through to the next chunk on N64
// get an explicit branch written there, since these are separate arrays here.
Gfx D_09000918_3544C8[92] = {
    gsSPEndDisplayList(),
};
